[package]
name = "synedrion"
authors = ['Entropy Cryptography <engineering@entropy.xyz>']
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "Threshold signing library based on Canetti-Gennaro-Goldfeder-Makriyannis-Peled '21 scheme"
repository = "https://github.com/entropyxyz/synedrion"
readme = "README.md"
categories = ["cryptography", "no-std"]

[dependencies]
signature = { version = "2.3.0-pre.4", default-features = false, features = ["alloc"] }
k256 = {git = "https://github.com/RustCrypto/elliptic-curves", default-features = false, features = ["ecdsa", "arithmetic"]}
rand_core = { version = "0.6.4", default-features = false, features = ["getrandom"] } # need "getrandom"?
sha2 = { version = "0.11.0-pre.3", default-features = false }
sha3 = { version = "0.11.0-pre.4", default-features = false }
digest = { version = "0.11.0-pre.9", default-features = false, features = ["alloc"]}
hex = { version = "0.4", default-features = false, features = ["alloc"] }
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
# TODO(dp): Make a PR to update this crate and remove the vendorized copy
hashing-serializer = { version = "0.1", default-features = false }
secrecy = { version = "0.8", default-features = false, features = ["alloc", "serde"] }
zeroize = { version = "1.8", default-features = false, features = ["alloc", "zeroize_derive"] }
bip32 = { version = "0.5.2", default-features = false, features = ["alloc", "secp256k1", "k256"] }

# Note: `alloc` is needed for `crytpto-bigint`'s dependency `serdect` to be able
# to serialize Uints in human-readable formats.
crypto-bigint = { version = "0.6.0-rc.2", features = ["serde", "alloc", "rand_core"] }
crypto-primes = "0.6.0-pre.0"

serde = { version = "1", default-features = false, features = ["derive"] }
bincode = "1"
cfg-if = "1" # neeed this?
itertools = { version = "0.13.0", default-features = false, optional = true } # need this?
displaydoc = { version = "0.2", default-features = false}

[dev-dependencies]
num-bigint = "0.4" # need this?
num-integer = "0.1" # need this?
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
rand = "0.8"
rand_chacha = "0.3"
criterion = "0.5"
itertools = "0.13.0" # need this?
k256 = {git = "https://github.com/RustCrypto/elliptic-curves", default-features = false, features = ["ecdsa", "serde", "pem"]}
impls = "1"

[features]
bench-internals = [] # makes some internal functions public to allow external benchmarks

[[bench]]
bench = true
name = "bench"
harness = false
required-features = ["bench-internals"]
path = "benches/bench.rs"
